// This file was automatically generated by genny.
// Any changes will be lost if this file is regenerated.
// see https://github.com/cheekybits/genny

package jsonrpc2

import (
	api "github.com/powerman/go-monolith-example/api/jsonrpc2-example"
	"github.com/powerman/go-monolith-example/internal/dom"
	"github.com/powerman/go-monolith-example/internal/jsonrpc2x"
	"github.com/powerman/go-monolith-example/ms/example/internal/app"
)

// IncExample implements JSON-RPC 2.0 method.
func (srv *Server) IncExample(arg api.RPCIncExampleReq, res *api.RPCIncExampleResp) error {
	ctx, log, methodName, auth, err := arg.NewContext(srv.authn, app.ServiceName)
	validateErr := jsonrpc2x.MakeValidateErr(log, srv.cfg.StrictErr, api.ErrsExtra["RPC."+methodName])
	recovery := jsonrpc2x.MakeRecovery(log, app.Metric)
	metrics := jsonrpc2x.MakeMetrics(metric, "RPC."+methodName)
	accessLog := jsonrpc2x.MakeAccessLog(log)
	handler := validateErr(recovery(metrics(jsonrpc2x.APIErr(apiErr(accessLog(func() error {
		if err != nil {
			return err
		}
		if auth.UserID == dom.NoUserID {
			return api.ErrUnauthorized
		}
		return srv.doIncExample(ctx, auth, arg, res)
	}))))))
	return handler()
}
