// This file was automatically generated by genny.
// Any changes will be lost if this file is regenerated.
// see https://github.com/cheekybits/genny


package jsonrpc2

import (
	"errors"

	api "github.com/powerman/go-monolith-example/api/jsonrpc2-example"
	"github.com/powerman/go-monolith-example/internal/apix"
	"github.com/powerman/go-monolith-example/internal/dom"
	"github.com/powerman/go-monolith-example/ms/example/internal/app"
	"github.com/powerman/go-monolith-example/pkg/jsonrpc2x"
)

// IncExample implements JSON-RPC 2.0 method.
func (srv *Server) IncExample(arg api.RPCIncExampleReq, res *api.RPCIncExampleResp) error {
	ctx, log, methodName, auth, err := arg.NewContext(srv.authn, app.ServiceName)
	validateErr := jsonrpc2x.MakeValidateErr(log, srv.cfg.StrictErr, api.ErrsCommon, api.ErrsExtra["RPC."+methodName])
	recovery := jsonrpc2x.MakeRecovery(log, app.Metric)
	metrics := jsonrpc2x.MakeMetrics(metric, "RPC."+methodName)
	accessLog := jsonrpc2x.MakeAccessLog(log)
	handler := validateErr(recovery(metrics(apiErr(accessLog(func() error {
		switch {
		case errors.Is(err, apix.ErrAccessTokenInvalid):
			return api.ErrUnauthorized
		case err != nil: // Any other error from authn is considered temporary.
			return api.ErrTryAgainLater
		case auth.UserName == dom.NoUser: // Authenticated but anon user (visitor).
			return api.ErrUnauthorized
		}
		return srv.doIncExample(ctx, auth, arg, res)
	})))))
	return handler()
}
