// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.26.0-devel
// 	protoc        v3.17.1
// source: powerman/example/auth/service.proto

package api

import (
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	_ "google.golang.org/protobuf/types/known/emptypb"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Possible roles for a user.
// New values may be added in the future.
type Access_Role int32

const (
	// Default value. This value is unused.
	Access_ROLE_UNSPECIFIED Access_Role = 0
	// Full access to everything.
	Access_ROLE_ADMIN Access_Role = 1
	// Full access only to user's own data.
	// Read-only access to user's Access.
	Access_ROLE_USER Access_Role = 2
)

// Enum value maps for Access_Role.
var (
	Access_Role_name = map[int32]string{
		0: "ROLE_UNSPECIFIED",
		1: "ROLE_ADMIN",
		2: "ROLE_USER",
	}
	Access_Role_value = map[string]int32{
		"ROLE_UNSPECIFIED": 0,
		"ROLE_ADMIN":       1,
		"ROLE_USER":        2,
	}
)

func (x Access_Role) Enum() *Access_Role {
	p := new(Access_Role)
	*p = x
	return p
}

func (x Access_Role) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Access_Role) Descriptor() protoreflect.EnumDescriptor {
	return file_powerman_example_auth_service_proto_enumTypes[0].Descriptor()
}

func (Access_Role) Type() protoreflect.EnumType {
	return &file_powerman_example_auth_service_proto_enumTypes[0]
}

func (x Access_Role) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Access_Role.Descriptor instead.
func (Access_Role) EnumDescriptor() ([]byte, []int) {
	return file_powerman_example_auth_service_proto_rawDescGZIP(), []int{7, 0}
}

// Request.
type CreateAccountRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// The account to create.
	Account *Account `protobuf:"bytes,1,opt,name=account,proto3" json:"account,omitempty"`
	// The ID to use for the account.
	// This value should be 4-63 characters [a-z0-9-].
	AccountId string `protobuf:"bytes,2,opt,name=account_id,json=accountId,proto3" json:"account_id,omitempty"`
}

func (x *CreateAccountRequest) Reset() {
	*x = CreateAccountRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_powerman_example_auth_service_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateAccountRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateAccountRequest) ProtoMessage() {}

func (x *CreateAccountRequest) ProtoReflect() protoreflect.Message {
	mi := &file_powerman_example_auth_service_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateAccountRequest.ProtoReflect.Descriptor instead.
func (*CreateAccountRequest) Descriptor() ([]byte, []int) {
	return file_powerman_example_auth_service_proto_rawDescGZIP(), []int{0}
}

func (x *CreateAccountRequest) GetAccount() *Account {
	if x != nil {
		return x.Account
	}
	return nil
}

func (x *CreateAccountRequest) GetAccountId() string {
	if x != nil {
		return x.AccountId
	}
	return ""
}

// Request.
type SigninIdentityRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Different ways to authenticate.
	//
	// Types that are assignable to Auth:
	//	*SigninIdentityRequest_Account
	//	*SigninIdentityRequest_Email
	Auth isSigninIdentityRequest_Auth `protobuf_oneof:"auth"`
}

func (x *SigninIdentityRequest) Reset() {
	*x = SigninIdentityRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_powerman_example_auth_service_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SigninIdentityRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SigninIdentityRequest) ProtoMessage() {}

func (x *SigninIdentityRequest) ProtoReflect() protoreflect.Message {
	mi := &file_powerman_example_auth_service_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SigninIdentityRequest.ProtoReflect.Descriptor instead.
func (*SigninIdentityRequest) Descriptor() ([]byte, []int) {
	return file_powerman_example_auth_service_proto_rawDescGZIP(), []int{1}
}

func (m *SigninIdentityRequest) GetAuth() isSigninIdentityRequest_Auth {
	if m != nil {
		return m.Auth
	}
	return nil
}

func (x *SigninIdentityRequest) GetAccount() *SigninIdentityRequest_AccountAuth {
	if x, ok := x.GetAuth().(*SigninIdentityRequest_Account); ok {
		return x.Account
	}
	return nil
}

func (x *SigninIdentityRequest) GetEmail() *SigninIdentityRequest_EmailAuth {
	if x, ok := x.GetAuth().(*SigninIdentityRequest_Email); ok {
		return x.Email
	}
	return nil
}

type isSigninIdentityRequest_Auth interface {
	isSigninIdentityRequest_Auth()
}

type SigninIdentityRequest_Account struct {
	// By username.
	Account *SigninIdentityRequest_AccountAuth `protobuf:"bytes,1,opt,name=account,proto3,oneof"`
}

type SigninIdentityRequest_Email struct {
	// By email.
	Email *SigninIdentityRequest_EmailAuth `protobuf:"bytes,2,opt,name=email,proto3,oneof"`
}

func (*SigninIdentityRequest_Account) isSigninIdentityRequest_Auth() {}

func (*SigninIdentityRequest_Email) isSigninIdentityRequest_Auth() {}

// Response.
type SigninIdentityResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Opaque.
	AccessToken string `protobuf:"bytes,1,opt,name=access_token,json=accessToken,proto3" json:"access_token,omitempty"`
	// User/Access details.
	User *User `protobuf:"bytes,2,opt,name=user,proto3" json:"user,omitempty"`
}

func (x *SigninIdentityResponse) Reset() {
	*x = SigninIdentityResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_powerman_example_auth_service_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SigninIdentityResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SigninIdentityResponse) ProtoMessage() {}

func (x *SigninIdentityResponse) ProtoReflect() protoreflect.Message {
	mi := &file_powerman_example_auth_service_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SigninIdentityResponse.ProtoReflect.Descriptor instead.
func (*SigninIdentityResponse) Descriptor() ([]byte, []int) {
	return file_powerman_example_auth_service_proto_rawDescGZIP(), []int{2}
}

func (x *SigninIdentityResponse) GetAccessToken() string {
	if x != nil {
		return x.AccessToken
	}
	return ""
}

func (x *SigninIdentityResponse) GetUser() *User {
	if x != nil {
		return x.User
	}
	return nil
}

// Request.
type SignoutIdentityRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Set to true to invalidate all user's access_token.
	Everywhere bool `protobuf:"varint,1,opt,name=everywhere,proto3" json:"everywhere,omitempty"`
}

func (x *SignoutIdentityRequest) Reset() {
	*x = SignoutIdentityRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_powerman_example_auth_service_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SignoutIdentityRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SignoutIdentityRequest) ProtoMessage() {}

func (x *SignoutIdentityRequest) ProtoReflect() protoreflect.Message {
	mi := &file_powerman_example_auth_service_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SignoutIdentityRequest.ProtoReflect.Descriptor instead.
func (*SignoutIdentityRequest) Descriptor() ([]byte, []int) {
	return file_powerman_example_auth_service_proto_rawDescGZIP(), []int{3}
}

func (x *SignoutIdentityRequest) GetEverywhere() bool {
	if x != nil {
		return x.Everywhere
	}
	return false
}

// Response.
type SignoutIdentityResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *SignoutIdentityResponse) Reset() {
	*x = SignoutIdentityResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_powerman_example_auth_service_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SignoutIdentityResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SignoutIdentityResponse) ProtoMessage() {}

func (x *SignoutIdentityResponse) ProtoReflect() protoreflect.Message {
	mi := &file_powerman_example_auth_service_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SignoutIdentityResponse.ProtoReflect.Descriptor instead.
func (*SignoutIdentityResponse) Descriptor() ([]byte, []int) {
	return file_powerman_example_auth_service_proto_rawDescGZIP(), []int{4}
}

// Account contains data needed for authentication.
type Account struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Format: "accounts/{account_id}".
	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	// Default identity connected to the account.
	User *User `protobuf:"bytes,2,opt,name=user,proto3" json:"user,omitempty"`
	// Must be strong enough.
	Password string `protobuf:"bytes,16,opt,name=password,proto3" json:"password,omitempty"`
	// Primary email, needed to reset password.
	Email string `protobuf:"bytes,3,opt,name=email,proto3" json:"email,omitempty"`
	// Account create time.
	// Output only.
	CreateTime *timestamppb.Timestamp `protobuf:"bytes,15,opt,name=create_time,json=createTime,proto3" json:"create_time,omitempty"`
}

func (x *Account) Reset() {
	*x = Account{}
	if protoimpl.UnsafeEnabled {
		mi := &file_powerman_example_auth_service_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Account) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Account) ProtoMessage() {}

func (x *Account) ProtoReflect() protoreflect.Message {
	mi := &file_powerman_example_auth_service_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Account.ProtoReflect.Descriptor instead.
func (*Account) Descriptor() ([]byte, []int) {
	return file_powerman_example_auth_service_proto_rawDescGZIP(), []int{5}
}

func (x *Account) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Account) GetUser() *User {
	if x != nil {
		return x.User
	}
	return nil
}

func (x *Account) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

func (x *Account) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *Account) GetCreateTime() *timestamppb.Timestamp {
	if x != nil {
		return x.CreateTime
	}
	return nil
}

// User is an identity tied to Account.
type User struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Format: "users/{user_uid}".
	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	// By default set to {account_id}.
	DisplayName string `protobuf:"bytes,2,opt,name=display_name,json=displayName,proto3" json:"display_name,omitempty"`
	// Permissions.
	Access *Access `protobuf:"bytes,3,opt,name=access,proto3" json:"access,omitempty"`
}

func (x *User) Reset() {
	*x = User{}
	if protoimpl.UnsafeEnabled {
		mi := &file_powerman_example_auth_service_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *User) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*User) ProtoMessage() {}

func (x *User) ProtoReflect() protoreflect.Message {
	mi := &file_powerman_example_auth_service_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use User.ProtoReflect.Descriptor instead.
func (*User) Descriptor() ([]byte, []int) {
	return file_powerman_example_auth_service_proto_rawDescGZIP(), []int{6}
}

func (x *User) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *User) GetDisplayName() string {
	if x != nil {
		return x.DisplayName
	}
	return ""
}

func (x *User) GetAccess() *Access {
	if x != nil {
		return x.Access
	}
	return nil
}

// Access describes identity's permissions.
type Access struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// User's role.
	Role Access_Role `protobuf:"varint,1,opt,name=role,proto3,enum=powerman.example.auth.Access_Role" json:"role,omitempty"`
}

func (x *Access) Reset() {
	*x = Access{}
	if protoimpl.UnsafeEnabled {
		mi := &file_powerman_example_auth_service_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Access) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Access) ProtoMessage() {}

func (x *Access) ProtoReflect() protoreflect.Message {
	mi := &file_powerman_example_auth_service_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Access.ProtoReflect.Descriptor instead.
func (*Access) Descriptor() ([]byte, []int) {
	return file_powerman_example_auth_service_proto_rawDescGZIP(), []int{7}
}

func (x *Access) GetRole() Access_Role {
	if x != nil {
		return x.Role
	}
	return Access_ROLE_UNSPECIFIED
}

// Authentication using username and password.
type SigninIdentityRequest_AccountAuth struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// This value should be 4-63 characters [a-z0-9-].
	AccountId string `protobuf:"bytes,1,opt,name=account_id,json=accountId,proto3" json:"account_id,omitempty"`
	// Any value.
	Password string `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`
}

func (x *SigninIdentityRequest_AccountAuth) Reset() {
	*x = SigninIdentityRequest_AccountAuth{}
	if protoimpl.UnsafeEnabled {
		mi := &file_powerman_example_auth_service_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SigninIdentityRequest_AccountAuth) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SigninIdentityRequest_AccountAuth) ProtoMessage() {}

func (x *SigninIdentityRequest_AccountAuth) ProtoReflect() protoreflect.Message {
	mi := &file_powerman_example_auth_service_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SigninIdentityRequest_AccountAuth.ProtoReflect.Descriptor instead.
func (*SigninIdentityRequest_AccountAuth) Descriptor() ([]byte, []int) {
	return file_powerman_example_auth_service_proto_rawDescGZIP(), []int{1, 0}
}

func (x *SigninIdentityRequest_AccountAuth) GetAccountId() string {
	if x != nil {
		return x.AccountId
	}
	return ""
}

func (x *SigninIdentityRequest_AccountAuth) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

// Authentication user email and password.
type SigninIdentityRequest_EmailAuth struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// This value should contain [@].
	Email string `protobuf:"bytes,1,opt,name=email,proto3" json:"email,omitempty"`
	// Any value.
	Password string `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`
}

func (x *SigninIdentityRequest_EmailAuth) Reset() {
	*x = SigninIdentityRequest_EmailAuth{}
	if protoimpl.UnsafeEnabled {
		mi := &file_powerman_example_auth_service_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SigninIdentityRequest_EmailAuth) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SigninIdentityRequest_EmailAuth) ProtoMessage() {}

func (x *SigninIdentityRequest_EmailAuth) ProtoReflect() protoreflect.Message {
	mi := &file_powerman_example_auth_service_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SigninIdentityRequest_EmailAuth.ProtoReflect.Descriptor instead.
func (*SigninIdentityRequest_EmailAuth) Descriptor() ([]byte, []int) {
	return file_powerman_example_auth_service_proto_rawDescGZIP(), []int{1, 1}
}

func (x *SigninIdentityRequest_EmailAuth) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *SigninIdentityRequest_EmailAuth) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

var File_powerman_example_auth_service_proto protoreflect.FileDescriptor

var file_powerman_example_auth_service_proto_rawDesc = []byte{
	0x0a, 0x23, 0x70, 0x6f, 0x77, 0x65, 0x72, 0x6d, 0x61, 0x6e, 0x2f, 0x65, 0x78, 0x61, 0x6d, 0x70,
	0x6c, 0x65, 0x2f, 0x61, 0x75, 0x74, 0x68, 0x2f, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x15, 0x70, 0x6f, 0x77, 0x65, 0x72, 0x6d, 0x61, 0x6e, 0x2e,
	0x65, 0x78, 0x61, 0x6d, 0x70, 0x6c, 0x65, 0x2e, 0x61, 0x75, 0x74, 0x68, 0x1a, 0x1c, 0x67, 0x6f,
	0x6f, 0x67, 0x6c, 0x65, 0x2f, 0x61, 0x70, 0x69, 0x2f, 0x61, 0x6e, 0x6e, 0x6f, 0x74, 0x61, 0x74,
	0x69, 0x6f, 0x6e, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x1f, 0x67, 0x6f, 0x6f, 0x67,
	0x6c, 0x65, 0x2f, 0x61, 0x70, 0x69, 0x2f, 0x66, 0x69, 0x65, 0x6c, 0x64, 0x5f, 0x62, 0x65, 0x68,
	0x61, 0x76, 0x69, 0x6f, 0x72, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x1b, 0x67, 0x6f, 0x6f,
	0x67, 0x6c, 0x65, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2f, 0x65, 0x6d, 0x70,
	0x74, 0x79, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x1f, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65,
	0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2f, 0x74, 0x69, 0x6d, 0x65, 0x73, 0x74,
	0x61, 0x6d, 0x70, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x75, 0x0a, 0x14, 0x43, 0x72, 0x65,
	0x61, 0x74, 0x65, 0x41, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x12, 0x3e, 0x0a, 0x07, 0x61, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x0b, 0x32, 0x1e, 0x2e, 0x70, 0x6f, 0x77, 0x65, 0x72, 0x6d, 0x61, 0x6e, 0x2e, 0x65, 0x78,
	0x61, 0x6d, 0x70, 0x6c, 0x65, 0x2e, 0x61, 0x75, 0x74, 0x68, 0x2e, 0x41, 0x63, 0x63, 0x6f, 0x75,
	0x6e, 0x74, 0x42, 0x04, 0xe2, 0x41, 0x01, 0x02, 0x52, 0x07, 0x61, 0x63, 0x63, 0x6f, 0x75, 0x6e,
	0x74, 0x12, 0x1d, 0x0a, 0x0a, 0x61, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x5f, 0x69, 0x64, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x61, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x49, 0x64,
	0x22, 0xce, 0x02, 0x0a, 0x15, 0x53, 0x69, 0x67, 0x6e, 0x69, 0x6e, 0x49, 0x64, 0x65, 0x6e, 0x74,
	0x69, 0x74, 0x79, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x54, 0x0a, 0x07, 0x61, 0x63,
	0x63, 0x6f, 0x75, 0x6e, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x38, 0x2e, 0x70, 0x6f,
	0x77, 0x65, 0x72, 0x6d, 0x61, 0x6e, 0x2e, 0x65, 0x78, 0x61, 0x6d, 0x70, 0x6c, 0x65, 0x2e, 0x61,
	0x75, 0x74, 0x68, 0x2e, 0x53, 0x69, 0x67, 0x6e, 0x69, 0x6e, 0x49, 0x64, 0x65, 0x6e, 0x74, 0x69,
	0x74, 0x79, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x2e, 0x41, 0x63, 0x63, 0x6f, 0x75, 0x6e,
	0x74, 0x41, 0x75, 0x74, 0x68, 0x48, 0x00, 0x52, 0x07, 0x61, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74,
	0x12, 0x4e, 0x0a, 0x05, 0x65, 0x6d, 0x61, 0x69, 0x6c, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32,
	0x36, 0x2e, 0x70, 0x6f, 0x77, 0x65, 0x72, 0x6d, 0x61, 0x6e, 0x2e, 0x65, 0x78, 0x61, 0x6d, 0x70,
	0x6c, 0x65, 0x2e, 0x61, 0x75, 0x74, 0x68, 0x2e, 0x53, 0x69, 0x67, 0x6e, 0x69, 0x6e, 0x49, 0x64,
	0x65, 0x6e, 0x74, 0x69, 0x74, 0x79, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x2e, 0x45, 0x6d,
	0x61, 0x69, 0x6c, 0x41, 0x75, 0x74, 0x68, 0x48, 0x00, 0x52, 0x05, 0x65, 0x6d, 0x61, 0x69, 0x6c,
	0x1a, 0x48, 0x0a, 0x0b, 0x41, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x41, 0x75, 0x74, 0x68, 0x12,
	0x1d, 0x0a, 0x0a, 0x61, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x09, 0x61, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x49, 0x64, 0x12, 0x1a,
	0x0a, 0x08, 0x70, 0x61, 0x73, 0x73, 0x77, 0x6f, 0x72, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x08, 0x70, 0x61, 0x73, 0x73, 0x77, 0x6f, 0x72, 0x64, 0x1a, 0x3d, 0x0a, 0x09, 0x45, 0x6d,
	0x61, 0x69, 0x6c, 0x41, 0x75, 0x74, 0x68, 0x12, 0x14, 0x0a, 0x05, 0x65, 0x6d, 0x61, 0x69, 0x6c,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x65, 0x6d, 0x61, 0x69, 0x6c, 0x12, 0x1a, 0x0a,
	0x08, 0x70, 0x61, 0x73, 0x73, 0x77, 0x6f, 0x72, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x08, 0x70, 0x61, 0x73, 0x73, 0x77, 0x6f, 0x72, 0x64, 0x42, 0x06, 0x0a, 0x04, 0x61, 0x75, 0x74,
	0x68, 0x22, 0x6c, 0x0a, 0x16, 0x53, 0x69, 0x67, 0x6e, 0x69, 0x6e, 0x49, 0x64, 0x65, 0x6e, 0x74,
	0x69, 0x74, 0x79, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x21, 0x0a, 0x0c, 0x61,
	0x63, 0x63, 0x65, 0x73, 0x73, 0x5f, 0x74, 0x6f, 0x6b, 0x65, 0x6e, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x0b, 0x61, 0x63, 0x63, 0x65, 0x73, 0x73, 0x54, 0x6f, 0x6b, 0x65, 0x6e, 0x12, 0x2f,
	0x0a, 0x04, 0x75, 0x73, 0x65, 0x72, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1b, 0x2e, 0x70,
	0x6f, 0x77, 0x65, 0x72, 0x6d, 0x61, 0x6e, 0x2e, 0x65, 0x78, 0x61, 0x6d, 0x70, 0x6c, 0x65, 0x2e,
	0x61, 0x75, 0x74, 0x68, 0x2e, 0x55, 0x73, 0x65, 0x72, 0x52, 0x04, 0x75, 0x73, 0x65, 0x72, 0x22,
	0x38, 0x0a, 0x16, 0x53, 0x69, 0x67, 0x6e, 0x6f, 0x75, 0x74, 0x49, 0x64, 0x65, 0x6e, 0x74, 0x69,
	0x74, 0x79, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x1e, 0x0a, 0x0a, 0x65, 0x76, 0x65,
	0x72, 0x79, 0x77, 0x68, 0x65, 0x72, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x08, 0x52, 0x0a, 0x65,
	0x76, 0x65, 0x72, 0x79, 0x77, 0x68, 0x65, 0x72, 0x65, 0x22, 0x19, 0x0a, 0x17, 0x53, 0x69, 0x67,
	0x6e, 0x6f, 0x75, 0x74, 0x49, 0x64, 0x65, 0x6e, 0x74, 0x69, 0x74, 0x79, 0x52, 0x65, 0x73, 0x70,
	0x6f, 0x6e, 0x73, 0x65, 0x22, 0xc9, 0x01, 0x0a, 0x07, 0x41, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74,
	0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04,
	0x6e, 0x61, 0x6d, 0x65, 0x12, 0x2f, 0x0a, 0x04, 0x75, 0x73, 0x65, 0x72, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x0b, 0x32, 0x1b, 0x2e, 0x70, 0x6f, 0x77, 0x65, 0x72, 0x6d, 0x61, 0x6e, 0x2e, 0x65, 0x78,
	0x61, 0x6d, 0x70, 0x6c, 0x65, 0x2e, 0x61, 0x75, 0x74, 0x68, 0x2e, 0x55, 0x73, 0x65, 0x72, 0x52,
	0x04, 0x75, 0x73, 0x65, 0x72, 0x12, 0x20, 0x0a, 0x08, 0x70, 0x61, 0x73, 0x73, 0x77, 0x6f, 0x72,
	0x64, 0x18, 0x10, 0x20, 0x01, 0x28, 0x09, 0x42, 0x04, 0xe2, 0x41, 0x01, 0x04, 0x52, 0x08, 0x70,
	0x61, 0x73, 0x73, 0x77, 0x6f, 0x72, 0x64, 0x12, 0x14, 0x0a, 0x05, 0x65, 0x6d, 0x61, 0x69, 0x6c,
	0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x65, 0x6d, 0x61, 0x69, 0x6c, 0x12, 0x41, 0x0a,
	0x0b, 0x63, 0x72, 0x65, 0x61, 0x74, 0x65, 0x5f, 0x74, 0x69, 0x6d, 0x65, 0x18, 0x0f, 0x20, 0x01,
	0x28, 0x0b, 0x32, 0x1a, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x62, 0x75, 0x66, 0x2e, 0x54, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x42, 0x04,
	0xe2, 0x41, 0x01, 0x03, 0x52, 0x0a, 0x63, 0x72, 0x65, 0x61, 0x74, 0x65, 0x54, 0x69, 0x6d, 0x65,
	0x22, 0x74, 0x0a, 0x04, 0x55, 0x73, 0x65, 0x72, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x21, 0x0a, 0x0c,
	0x64, 0x69, 0x73, 0x70, 0x6c, 0x61, 0x79, 0x5f, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x0b, 0x64, 0x69, 0x73, 0x70, 0x6c, 0x61, 0x79, 0x4e, 0x61, 0x6d, 0x65, 0x12,
	0x35, 0x0a, 0x06, 0x61, 0x63, 0x63, 0x65, 0x73, 0x73, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0b, 0x32,
	0x1d, 0x2e, 0x70, 0x6f, 0x77, 0x65, 0x72, 0x6d, 0x61, 0x6e, 0x2e, 0x65, 0x78, 0x61, 0x6d, 0x70,
	0x6c, 0x65, 0x2e, 0x61, 0x75, 0x74, 0x68, 0x2e, 0x41, 0x63, 0x63, 0x65, 0x73, 0x73, 0x52, 0x06,
	0x61, 0x63, 0x63, 0x65, 0x73, 0x73, 0x22, 0x7d, 0x0a, 0x06, 0x41, 0x63, 0x63, 0x65, 0x73, 0x73,
	0x12, 0x36, 0x0a, 0x04, 0x72, 0x6f, 0x6c, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x22,
	0x2e, 0x70, 0x6f, 0x77, 0x65, 0x72, 0x6d, 0x61, 0x6e, 0x2e, 0x65, 0x78, 0x61, 0x6d, 0x70, 0x6c,
	0x65, 0x2e, 0x61, 0x75, 0x74, 0x68, 0x2e, 0x41, 0x63, 0x63, 0x65, 0x73, 0x73, 0x2e, 0x52, 0x6f,
	0x6c, 0x65, 0x52, 0x04, 0x72, 0x6f, 0x6c, 0x65, 0x22, 0x3b, 0x0a, 0x04, 0x52, 0x6f, 0x6c, 0x65,
	0x12, 0x14, 0x0a, 0x10, 0x52, 0x4f, 0x4c, 0x45, 0x5f, 0x55, 0x4e, 0x53, 0x50, 0x45, 0x43, 0x49,
	0x46, 0x49, 0x45, 0x44, 0x10, 0x00, 0x12, 0x0e, 0x0a, 0x0a, 0x52, 0x4f, 0x4c, 0x45, 0x5f, 0x41,
	0x44, 0x4d, 0x49, 0x4e, 0x10, 0x01, 0x12, 0x0d, 0x0a, 0x09, 0x52, 0x4f, 0x4c, 0x45, 0x5f, 0x55,
	0x53, 0x45, 0x52, 0x10, 0x02, 0x32, 0x9a, 0x02, 0x0a, 0x09, 0x4e, 0x6f, 0x41, 0x75, 0x74, 0x68,
	0x53, 0x76, 0x63, 0x12, 0x78, 0x0a, 0x0d, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x41, 0x63, 0x63,
	0x6f, 0x75, 0x6e, 0x74, 0x12, 0x2b, 0x2e, 0x70, 0x6f, 0x77, 0x65, 0x72, 0x6d, 0x61, 0x6e, 0x2e,
	0x65, 0x78, 0x61, 0x6d, 0x70, 0x6c, 0x65, 0x2e, 0x61, 0x75, 0x74, 0x68, 0x2e, 0x43, 0x72, 0x65,
	0x61, 0x74, 0x65, 0x41, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x1a, 0x1e, 0x2e, 0x70, 0x6f, 0x77, 0x65, 0x72, 0x6d, 0x61, 0x6e, 0x2e, 0x65, 0x78, 0x61,
	0x6d, 0x70, 0x6c, 0x65, 0x2e, 0x61, 0x75, 0x74, 0x68, 0x2e, 0x41, 0x63, 0x63, 0x6f, 0x75, 0x6e,
	0x74, 0x22, 0x1a, 0x82, 0xd3, 0xe4, 0x93, 0x02, 0x14, 0x22, 0x09, 0x2f, 0x61, 0x63, 0x63, 0x6f,
	0x75, 0x6e, 0x74, 0x73, 0x3a, 0x07, 0x61, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x12, 0x92, 0x01,
	0x0a, 0x0e, 0x53, 0x69, 0x67, 0x6e, 0x69, 0x6e, 0x49, 0x64, 0x65, 0x6e, 0x74, 0x69, 0x74, 0x79,
	0x12, 0x2c, 0x2e, 0x70, 0x6f, 0x77, 0x65, 0x72, 0x6d, 0x61, 0x6e, 0x2e, 0x65, 0x78, 0x61, 0x6d,
	0x70, 0x6c, 0x65, 0x2e, 0x61, 0x75, 0x74, 0x68, 0x2e, 0x53, 0x69, 0x67, 0x6e, 0x69, 0x6e, 0x49,
	0x64, 0x65, 0x6e, 0x74, 0x69, 0x74, 0x79, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x2d,
	0x2e, 0x70, 0x6f, 0x77, 0x65, 0x72, 0x6d, 0x61, 0x6e, 0x2e, 0x65, 0x78, 0x61, 0x6d, 0x70, 0x6c,
	0x65, 0x2e, 0x61, 0x75, 0x74, 0x68, 0x2e, 0x53, 0x69, 0x67, 0x6e, 0x69, 0x6e, 0x49, 0x64, 0x65,
	0x6e, 0x74, 0x69, 0x74, 0x79, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x23, 0x82,
	0xd3, 0xe4, 0x93, 0x02, 0x1d, 0x22, 0x18, 0x2f, 0x61, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x73,
	0x3a, 0x73, 0x69, 0x67, 0x6e, 0x69, 0x6e, 0x49, 0x64, 0x65, 0x6e, 0x74, 0x69, 0x74, 0x79, 0x3a,
	0x01, 0x2a, 0x32, 0xa2, 0x01, 0x0a, 0x07, 0x41, 0x75, 0x74, 0x68, 0x53, 0x76, 0x63, 0x12, 0x96,
	0x01, 0x0a, 0x0f, 0x53, 0x69, 0x67, 0x6e, 0x6f, 0x75, 0x74, 0x49, 0x64, 0x65, 0x6e, 0x74, 0x69,
	0x74, 0x79, 0x12, 0x2d, 0x2e, 0x70, 0x6f, 0x77, 0x65, 0x72, 0x6d, 0x61, 0x6e, 0x2e, 0x65, 0x78,
	0x61, 0x6d, 0x70, 0x6c, 0x65, 0x2e, 0x61, 0x75, 0x74, 0x68, 0x2e, 0x53, 0x69, 0x67, 0x6e, 0x6f,
	0x75, 0x74, 0x49, 0x64, 0x65, 0x6e, 0x74, 0x69, 0x74, 0x79, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x1a, 0x2e, 0x2e, 0x70, 0x6f, 0x77, 0x65, 0x72, 0x6d, 0x61, 0x6e, 0x2e, 0x65, 0x78, 0x61,
	0x6d, 0x70, 0x6c, 0x65, 0x2e, 0x61, 0x75, 0x74, 0x68, 0x2e, 0x53, 0x69, 0x67, 0x6e, 0x6f, 0x75,
	0x74, 0x49, 0x64, 0x65, 0x6e, 0x74, 0x69, 0x74, 0x79, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73,
	0x65, 0x22, 0x24, 0x82, 0xd3, 0xe4, 0x93, 0x02, 0x1e, 0x22, 0x19, 0x2f, 0x61, 0x63, 0x63, 0x6f,
	0x75, 0x6e, 0x74, 0x73, 0x3a, 0x73, 0x69, 0x67, 0x6e, 0x6f, 0x75, 0x74, 0x49, 0x64, 0x65, 0x6e,
	0x74, 0x69, 0x74, 0x79, 0x3a, 0x01, 0x2a, 0x42, 0x4d, 0x5a, 0x4b, 0x67, 0x69, 0x74, 0x68, 0x75,
	0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x70, 0x6f, 0x77, 0x65, 0x72, 0x6d, 0x61, 0x6e, 0x2f, 0x67,
	0x6f, 0x2d, 0x6d, 0x6f, 0x6e, 0x6f, 0x6c, 0x69, 0x74, 0x68, 0x2d, 0x65, 0x78, 0x61, 0x6d, 0x70,
	0x6c, 0x65, 0x2f, 0x61, 0x70, 0x69, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x70, 0x6f, 0x77,
	0x65, 0x72, 0x6d, 0x61, 0x6e, 0x2f, 0x65, 0x78, 0x61, 0x6d, 0x70, 0x6c, 0x65, 0x2f, 0x61, 0x75,
	0x74, 0x68, 0x3b, 0x61, 0x70, 0x69, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_powerman_example_auth_service_proto_rawDescOnce sync.Once
	file_powerman_example_auth_service_proto_rawDescData = file_powerman_example_auth_service_proto_rawDesc
)

func file_powerman_example_auth_service_proto_rawDescGZIP() []byte {
	file_powerman_example_auth_service_proto_rawDescOnce.Do(func() {
		file_powerman_example_auth_service_proto_rawDescData = protoimpl.X.CompressGZIP(file_powerman_example_auth_service_proto_rawDescData)
	})
	return file_powerman_example_auth_service_proto_rawDescData
}

var file_powerman_example_auth_service_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_powerman_example_auth_service_proto_msgTypes = make([]protoimpl.MessageInfo, 10)
var file_powerman_example_auth_service_proto_goTypes = []interface{}{
	(Access_Role)(0),                          // 0: powerman.example.auth.Access.Role
	(*CreateAccountRequest)(nil),              // 1: powerman.example.auth.CreateAccountRequest
	(*SigninIdentityRequest)(nil),             // 2: powerman.example.auth.SigninIdentityRequest
	(*SigninIdentityResponse)(nil),            // 3: powerman.example.auth.SigninIdentityResponse
	(*SignoutIdentityRequest)(nil),            // 4: powerman.example.auth.SignoutIdentityRequest
	(*SignoutIdentityResponse)(nil),           // 5: powerman.example.auth.SignoutIdentityResponse
	(*Account)(nil),                           // 6: powerman.example.auth.Account
	(*User)(nil),                              // 7: powerman.example.auth.User
	(*Access)(nil),                            // 8: powerman.example.auth.Access
	(*SigninIdentityRequest_AccountAuth)(nil), // 9: powerman.example.auth.SigninIdentityRequest.AccountAuth
	(*SigninIdentityRequest_EmailAuth)(nil),   // 10: powerman.example.auth.SigninIdentityRequest.EmailAuth
	(*timestamppb.Timestamp)(nil),             // 11: google.protobuf.Timestamp
}
var file_powerman_example_auth_service_proto_depIdxs = []int32{
	6,  // 0: powerman.example.auth.CreateAccountRequest.account:type_name -> powerman.example.auth.Account
	9,  // 1: powerman.example.auth.SigninIdentityRequest.account:type_name -> powerman.example.auth.SigninIdentityRequest.AccountAuth
	10, // 2: powerman.example.auth.SigninIdentityRequest.email:type_name -> powerman.example.auth.SigninIdentityRequest.EmailAuth
	7,  // 3: powerman.example.auth.SigninIdentityResponse.user:type_name -> powerman.example.auth.User
	7,  // 4: powerman.example.auth.Account.user:type_name -> powerman.example.auth.User
	11, // 5: powerman.example.auth.Account.create_time:type_name -> google.protobuf.Timestamp
	8,  // 6: powerman.example.auth.User.access:type_name -> powerman.example.auth.Access
	0,  // 7: powerman.example.auth.Access.role:type_name -> powerman.example.auth.Access.Role
	1,  // 8: powerman.example.auth.NoAuthSvc.CreateAccount:input_type -> powerman.example.auth.CreateAccountRequest
	2,  // 9: powerman.example.auth.NoAuthSvc.SigninIdentity:input_type -> powerman.example.auth.SigninIdentityRequest
	4,  // 10: powerman.example.auth.AuthSvc.SignoutIdentity:input_type -> powerman.example.auth.SignoutIdentityRequest
	6,  // 11: powerman.example.auth.NoAuthSvc.CreateAccount:output_type -> powerman.example.auth.Account
	3,  // 12: powerman.example.auth.NoAuthSvc.SigninIdentity:output_type -> powerman.example.auth.SigninIdentityResponse
	5,  // 13: powerman.example.auth.AuthSvc.SignoutIdentity:output_type -> powerman.example.auth.SignoutIdentityResponse
	11, // [11:14] is the sub-list for method output_type
	8,  // [8:11] is the sub-list for method input_type
	8,  // [8:8] is the sub-list for extension type_name
	8,  // [8:8] is the sub-list for extension extendee
	0,  // [0:8] is the sub-list for field type_name
}

func init() { file_powerman_example_auth_service_proto_init() }
func file_powerman_example_auth_service_proto_init() {
	if File_powerman_example_auth_service_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_powerman_example_auth_service_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreateAccountRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_powerman_example_auth_service_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SigninIdentityRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_powerman_example_auth_service_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SigninIdentityResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_powerman_example_auth_service_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SignoutIdentityRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_powerman_example_auth_service_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SignoutIdentityResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_powerman_example_auth_service_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Account); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_powerman_example_auth_service_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*User); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_powerman_example_auth_service_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Access); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_powerman_example_auth_service_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SigninIdentityRequest_AccountAuth); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_powerman_example_auth_service_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SigninIdentityRequest_EmailAuth); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	file_powerman_example_auth_service_proto_msgTypes[1].OneofWrappers = []interface{}{
		(*SigninIdentityRequest_Account)(nil),
		(*SigninIdentityRequest_Email)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_powerman_example_auth_service_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   10,
			NumExtensions: 0,
			NumServices:   2,
		},
		GoTypes:           file_powerman_example_auth_service_proto_goTypes,
		DependencyIndexes: file_powerman_example_auth_service_proto_depIdxs,
		EnumInfos:         file_powerman_example_auth_service_proto_enumTypes,
		MessageInfos:      file_powerman_example_auth_service_proto_msgTypes,
	}.Build()
	File_powerman_example_auth_service_proto = out.File
	file_powerman_example_auth_service_proto_rawDesc = nil
	file_powerman_example_auth_service_proto_goTypes = nil
	file_powerman_example_auth_service_proto_depIdxs = nil
}
