// Code generated by "stringer -output=stringer.Role.go -type=Role -trimprefix=Role"; DO NOT EDIT.

package app

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[RoleAdmin-1]
	_ = x[RoleUser-2]
	_ = x[roleMax-3]
}

const _Role_name = "AdminUserroleMax"

var _Role_index = [...]uint8{0, 5, 9, 16}

func (i Role) String() string {
	i -= 1
	if i < 0 || i >= Role(len(_Role_index)-1) {
		return "Role(" + strconv.FormatInt(int64(i+1), 10) + ")"
	}
	return _Role_name[_Role_index[i]:_Role_index[i+1]]
}
