// Package migrations provides goose migrations.
package migrations

import (
	goosepkg "github.com/powerman/goose/v2"

	"github.com/powerman/go-monolith-example/ms/example/internal/app"
	"github.com/powerman/go-monolith-example/pkg/def"
)

//nolint:gochecknoglobals // Force code generated by `goose create` to use instance.
var goose = def.NewGoose(app.ServiceName)

// Goose returns goose instance with Go migrations defined in the package.
func Goose() *goosepkg.Instance { return goose }
