// This file was automatically generated by genny.
// Any changes will be lost if this file is regenerated.
// see https://github.com/cheekybits/genny

package api

import (
	"github.com/powerman/go-monolith-example/internal/jsonrpc2x"
	"github.com/powerman/go-monolith-example/ms/example/internal/app"
	proto "github.com/powerman/go-monolith-example/proto/rpc-example"
)

// IncExample implements JSON-RPC 2.0 method.
func (api *API) IncExample(arg proto.APIIncExampleReq, res *proto.APIIncExampleResp) error {
	ctx, log, methodName, auth, err := arg.NewContext(api.authn, app.ServiceName)
	validateErr := jsonrpc2x.MakeValidateErr(log, api.strictErr, proto.ErrsExtra[methodName])
	recovery := jsonrpc2x.MakeRecovery(log, app.Metric)
	metrics := jsonrpc2x.MakeMetrics(metric, methodName)
	accessLog := jsonrpc2x.MakeAccessLog(log)
	handler := validateErr(recovery(metrics(protoErr(jsonrpc2x.ProtoErr(accessLog(func() error {
		if err != nil {
			return err
		}
		return api.doIncExample(ctx, auth, arg, res)
	}))))))
	return handler()
}
