// This file was automatically generated by genny.
// Any changes will be lost if this file is regenerated.
// see https://github.com/cheekybits/genny

package api

import (
	"github.com/powerman/go-monolith-example/internal/jsonrpc2x"
	"github.com/powerman/go-monolith-example/ms/example/internal/app"
	"github.com/powerman/go-monolith-example/proto/rpc"
)

// IncExample implements JSON-RPC 2.0 method.
func (api *API) IncExample(arg rpc.IncExampleReq, res *rpc.IncExampleResp) error {
	ctx, log, methodName, auth, err := arg.NewContext(app.ServiceName)
	recovery := jsonrpc2x.MakeRecovery(log, app.Metric)
	metrics := jsonrpc2x.MakeMetrics(metric, methodName)
	apiError := makeAPIError(rpc.ErrsExtra[methodName])
	accessLog := jsonrpc2x.MakeAccessLog(log)
	handler := recovery(metrics(apiError(accessLog(func() error {
		if err != nil {
			return err
		}
		return api.doIncExample(ctx, auth, arg, res)
	}))))
	return handler()
}
